#include "nsISupports.idl"

[scriptable, uuid(ffbf773b-89f8-4028-af84-ba7d847bfd05)]
interface hyIDataBuffer : nsISupports
{
  readonly attribute unsigned long long size;
  readonly attribute string buffer;
};
