#include "nsISupports.idl"
#include "hyIHttpHeaderFields.idl"

[scriptable, uuid(7f5612e4-1358-4f8c-a0e6-b4ddc5942b97)]
interface hyIHttpResponse {
    readonly attribute hyIAsciiString       responseHttpVersion;
    readonly attribute unsigned long        responseStatusCode;
    readonly attribute hyIAsciiString       responseStatusMessage;
};
