#include "nsISupports.idl"
#include "hyIHttpRequest.idl"
#include "hyIDataChannel.idl"

[scriptable, uuid(161613ed-7750-4fe5-8e22-39c33e07ba13)]
interface hyIHttpRequestChannelListener : nsISupports {
    void onHttpRequestReady(
        in hyIHttpRequest aRequest,
        
        /* 
         * This carries the actual HTTP content other than 
         * the header part. 
         */
        in hyIDataChannel aDataChannel, 

        in nsISupports aContext);
};
