#include "nsISupports.idl"
#include "hyITextChannelListener.idl"

[scriptable, uuid(3d1f7577-b5d5-45a9-9901-15590a8b4723)]
interface hyITextChannel : nsISupports
{
  void openTextChannel(in hyITextChannelListener aListener, in nsISupports aContext);
};
