#include "nsISupports.idl"
#include "hyIUnicodeString.idl"

[scriptable, uuid(785a0097-00f1-4090-8e63-19f66e7cdbe2)]
interface hyITextChannelListener : nsISupports
{
  void onTextDataReceive(in hyIUnicodeString aText, in nsISupports aContext);

  void onMalformedText(in nsISupports aContext);
};
