#include "nsISupports.idl"
#include "hyIAsciiString.idl"
#include "hyIUnicodeStringIterator.idl"
#include "hyIDataBuffer.idl"

[scriptable, uuid(926822ca-d6c5-41cf-ab27-e369d2cda450)]
interface hyIUnicodeString : nsISupports
{
  /*
   * The number of code points the Unicode string has.
   */
  readonly attribute unsigned long long length;

  /*
   * Creates an iterator that automatically decode and 
   * iterate through the Unicode string.
   */
  hyIUnicodeStringIterator iter();

  /*
   * Get the encoding name in the form of ASCII string.
   */
  readonly attribute hyIAsciiString encoding;

  /*
   * Get the raw buffer that contains the encoded raw bytes.
   */
  readonly attribute hyIDataBuffer buffer;

  bool equalCodepoint(in hyIUnicodeString aOther);
};
