#include "nsISupports.idl"
#include "hyIXmlChannelListener.idl"

[scriptable, uuid(c1678170-7139-4695-b742-75bf4965f19e)]
interface hyIXmlChannel : nsISupports
{
  void openXmlChannel(in hyIXmlChannelListener aListener, in nsISupports aContext);
};
